apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama-stack-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: llama-stack-k8s-operator-system
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: release
    repoURL: 'https://github.com/llamastack/llama-stack-k8s-operator.git'
    targetRevision: HEAD