apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: llamastackdistribution-sample
spec:
  replicas: 1
  server:
    distribution:
      name: remote-vllm
    containerSpec:
      port: 8321
      env:
      - name: INFERENCE_MODEL
        value: {{ .Values.llamastackdistribution.vllm.model }}
      - name: VLLM_URL
        value: {{ .Values.llamastackdistribution.vllm.url }}
    storage:
      size: "20Gi"
      mountPath: "/home/lls/.lls"
